name: CI

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master
      - release/*

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      CHILD_CONCURRENCY: "1"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    # TODO: rename azure-pipelines/linux/xvfb.init to github-actions
    - run: |
        sudo apt-get update
        sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
        sudo cp build/azure-pipelines/linux/xvfb.init /etc/init.d/xvfb
        sudo chmod +x /etc/init.d/xvfb
        sudo update-rc.d xvfb defaults
        sudo service xvfb start
      name: Setup Build Environment
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    # TODO: cache node modules
    - run: yarn --frozen-lockfile
      name: Install Dependencies
    - run: yarn electron x64
      name: Download Electron
    - run: yarn gulp hygiene
      name: Run Hygiene Checks
    - run: yarn monaco-compile-check
      name: Run Monaco Editor Checks
    - run: yarn valid-layers-check
      name: Run Valid Layers Checks
    - run: yarn compile
      name: Compile Sources
    - run: yarn download-builtin-extensions
      name: Download Built-in Extensions
    - name: Copy compiled result to directory of result
      run: |
        mkdir result
        cp package.json result
        cp -r out result
        cp -r scripts result
        cp -r extensions result
        mkdir result/src
        cp -r src/vs result/src
        mkdir result/remote
        cp -r remote/web result/remote
        cp -r resources result
        mkdir result/node_modules
        cp -r node_modules/opn result/node_modules
        cp -r node_modules/vscode-minimist result/node_modules
        cp -r node_modules/is-wsl result/node_modules
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.0.1
      with:
        username: ${{ secrets.user }}
        password: ${{ secrets.pw }}
        repository: phwhx/new-vscode
        tags: latest
        path: result

        
